-- 1. Create Tables
CREATE TABLE IF NOT EXISTS ad_spend (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  date DATE NOT NULL,
  spend_amount NUMERIC NOT NULL DEFAULT 0,
  campaign_id TEXT,
  impressions INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  date DATE NOT NULL,
  sale_amount NUMERIC NOT NULL DEFAULT 0,
  order_id TEXT,
  customer_email TEXT
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE ad_spend ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies

-- Ad Spend Policies
CREATE POLICY "Users can only view their own ad spend data"
ON ad_spend FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can only insert their own ad spend data"
ON ad_spend FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only update their own ad spend data"
ON ad_spend FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only delete their own ad spend data"
ON ad_spend FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- Sales Policies
CREATE POLICY "Users can only view their own sales data"
ON sales FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can only insert their own sales data"
ON sales FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only update their own sales data"
ON sales FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only delete their own sales data"
ON sales FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- 4. Ad Accounts Table for Integrations
CREATE TABLE IF NOT EXISTS ad_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  platform TEXT NOT NULL, -- 'google' or 'meta'
  external_account_id TEXT NOT NULL,
  account_name TEXT,
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  token_expires_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT TRUE,
  CONSTRAINT unique_platform_account UNIQUE(user_id, platform, external_account_id)
);

ALTER TABLE ad_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only view their own ad accounts"
ON ad_accounts FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can only insert their own ad accounts"
ON ad_accounts FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can only update their own ad accounts"
ON ad_accounts FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
